const UNIT = {
  meta: { id:'alicogia', title:'The Story of Ali Cogia, Merchant of Baghdad', benchmark:'ELA.10.R.1.1', benchmarkLabel:'Literary Elements', text:'One Thousand and One Nights', paragraphs:'1-8', days:6 },
  days: {
    1: {
      bellringer: { words:['contented','prosperous'], questions:[{stem:'Read: "In a city of Baghdad there lived a merchant named Ali Cogia, who having neither wife nor child, was in easy circumstances."  What does "easy circumstances" suggest about Ali Cogia?', options:[{letter:'A',text:'He lives a difficult life',correct:false},{letter:'B',text:'He is financially comfortable',correct:true},{letter:'C',text:'He works very hard',correct:false},{letter:'D',text:'He has many problems',correct:false}], writtenPrompt:'What does "contented" suggest about Ali Cogia\u2019s mindset?', writtenModel:'The word "contented" suggests that Ali Cogia is satisfied with his life. He is not seeking more wealth or status.'},{stem:'Read: "He was contented with the income he received from his business, but a dream he had three nights running disturbed his mind greatly."  What is the most likely meaning of "prosperous" based on context?', options:[{letter:'A',text:'Poor and struggling',correct:false},{letter:'B',text:'Successful and financially comfortable',correct:true},{letter:'C',text:'Tired and overworked',correct:false},{letter:'D',text:'Generous and kind',correct:false}], writtenPrompt:'How does the word "disturbed" affect the tone of this passage?', writtenModel:'The word "disturbed" creates an uneasy tone. Even though Ali Cogia is contented, the recurring dream suggests something is about to disrupt his peaceful life.'}] },
      vocabulary: [{word:'contented',partOfSpeech:'adjective',definition:'satisfied and at ease',exampleSentence:'She felt contented after finishing the long project.'},{word:'prosperous',partOfSpeech:'adjective',definition:'successful and wealthy',exampleSentence:'The prosperous merchant owned several ships.'}],
      organizer: { benchmarkFocus:'Literary Elements — Character', columns:['Element','Evidence from Text'], rows:[{label:'I Do',cells:['Character — Ali Cogia','Ali Cogia is described as a prosperous merchant who is contented with his life.'],isPreFilled:true},{label:'We Do',cells:['Setting',''],isPreFilled:false},{label:'You Do w/ Partner',cells:['Conflict',''],isPreFilled:false},{label:'You Do',cells:['Symbol',''],isPreFilled:false}] },
      teacherNotes: 'Model the I Do row using think-aloud: "I notice the author describes Ali Cogia as prosperous and contented. That tells me he has money and is happy. This characterization sets up the conflict." Release to We Do after modeling.',
      textPassage: { paragraphs:[{number:1,text:'In a city of Baghdad there lived a merchant named Ali Cogia, who having neither wife nor child, was in easy circumstances.'},{number:2,text:'He was contented with the income he received from his business, but a dream he had three nights running disturbed his mind greatly.'}], cubesGuide:[{letter:'C',action:'Circle unknown words',example:'contented, circumstances'},{letter:'U',action:'Underline key details about the character',example:'prosperous merchant, no wife or child'},{letter:'B',action:'Box the setting clues',example:'Baghdad'},{letter:'E',action:'Exclaim surprising or interesting details',example:'The same dream three nights running'}] },
      esol: { frames:[{level:'L1–L2',frame:'The character of ___ is shown as ___ because ___.'},{level:'L3–L4',frame:'The author reveals that ___ by describing him as ___, which suggests ___.'},{level:'L5',frame:'Through the characterization of ___, the author establishes ___ which foreshadows ___.'}], wordBank:['contented','prosperous','merchant','Baghdad','disturbed'], l1Note:'Visual dictionary available. Allow L1 students to respond in home language first.' },
      progressItems:['Bellringer complete (4 min)','I Do row modeled','We Do row complete','You Do w/ Partner complete','You Do complete']
    }
  },
  assessment: { stopProtocol:{description:'Use STOP to evaluate MC answer choices.',steps:[{letter:'S',label:'Silly',description:'Clearly wrong — eliminate first'},{letter:'T',label:'Tricky',description:'Plausible but unsupported by text'},{letter:'O',label:'Opposite',description:'Contradicts the text'},{letter:'P',label:'Proven',description:'Directly supported by text evidence'}]}, mcQuestions:[], raceGuide:{tiers:[{tier:'LITE (L2)',label:'Restate + Answer',frame:'The literary element ___ is shown when ___.'},{tier:'STANDARD (L3)',label:'RACE',frame:'The author uses ___ to show ___. The text states "___." This reveals ___.'}]}, achievementLevels:[] },
  downloads: [{label:'Teacher Lesson Plan',filename:'AliCogia_D1-6_TeacherPlan_20260308.docx'},{label:'Student Packet',filename:'AliCogia_D1-6_StudentPacket_20260308.docx'},{label:'Answer Key',filename:'AliCogia_D1-6_AnswerKey_20260308.docx'},{label:'Feedback Form',filename:'AliCogia_D1-6_FeedbackForm_20260308.docx'}]
};
